
spring:
  datasource:
    username: admin
    password: maxwit
    url: jdbc:mysql://localhost:3306/device
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: device-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
