spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/debug-live/config-demo.git
          search-paths: config-repo

server:
  port: 8802
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8801/eureka/
